execution_engine: asyncio
logger:
  transports: [file]
  level: debug
  path: "logs/mcp-agent.jsonl"

mcp:
  servers:
    fetch:
      command: "C:\\Users\\joelf\\.local\\bin\\uv.exe"
      args: ["tool", "run", "mcp-server-fetch"]
      description: "Fetch content at URLs from the world wide web"
    filesystem:
      command: "C:\\Program Files\\nodejs\\npx.cmd"
      args: [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          # Current directory will be added by the code
        ]
      description: "Read and write files on the filesystem"

openai:
  default_model: gpt-4o
  # Secrets are loaded from mcp_agent.secrets.yaml
